# numpy基礎課程(20分鐘)

In [1]:
import numpy as np
from PIL import Image
%matplotlib inline
import matplotlib.pyplot as plt


在進行後續課程前，您最需要知道關於numpy的幾個重要背景知識:
1. numpy這個字該怎麼發音?? **答案:"num-pie"(nəmpᴧɪ)**
2. 我該如何安裝??  **答案:pip install numpy**
3. 我想看他的代碼該去哪裡找?? **答案: https://github.com/numpy/numpy**
4. 為什麼numpy速度超快? **答案:他是基於底層c語言的計算引擎，因此效率極高**
5. 支持那些python版本? **答案：numpy團隊已經公布2020年起將不再支持python 2.7，建議你使用3.5或3.6**
6. 如何在python中引入numpy? **答案:在程式中加入import numpy as np(np是我們常用的簡稱)**

## 什麼是向量

<img style="float: left;" src="images/scalar2tensor.png">
<img style="float: left;" src="images/tensordog.jpg" >

## 如何建立一個向量

numpy所構成的數據結構型別為ndarray，要生成這樣結構最簡單的方式就是直接將list做轉換，你可以使用np.array或者是np.asarray來進行轉換。兩者其實最後產生的結果是一樣的，**唯一的差別則是在於np.array會從資料源複製一份占用了新的記憶體，而np.asarray則直接將原有資料轉換，不會耗用新的記憶體**。如果你後面還需要參照原始數據源，則建議使用np.array，但是缺點則是會占用多的記憶體。

In [2]:
x1=np.array([1,2,3,4,5])
print(x1)
x2=np.asarray([1,2,3,4,5])
print(x2)

[1 2 3 4 5]
[1 2 3 4 5]


## 向量的維度與形狀

In [3]:
x1=np.array([1,2,3])
x2=np.array([1,2,3,4,5])
print(x1.shape)
print(x1.ndim)
print(x2.shape)
print(x2.ndim)

(3,)
1
(5,)
1


In [14]:
x1=np.array([1,2,3,4,5])
x2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(x1.shape)
print(x2.shape)
print(x3.shape)

(5,)
(4, 3)
(1, 4, 3)


In [5]:
#習題作答區域



## 特殊結構的ndarray生成

剛剛介紹了如何從清單轉換為向量，但其實在numpy生成向量的方法可不只一種，接下來就要逐一介紹我個人在做深度學習時較常用的幾種。首先是在深度學習中經常會用到裡面的值全部為零(很多為了填滿固定形狀所以補零)或是全部為1的向量(例如要產生一個預設的權重序列，初始值就可以都用1)。**千萬記得權重的初始值千萬別全部是零，否則你會很快收到大量的nan....**。為了簡化這類型向量的生成，numpy很貼心的準備了np.zeros以及np.ones的函數，裡面只要填寫想要生成的形狀就可以自動產生。若你連形狀都懶得填，但是若你有一個參考用的向量，你也可以使用np.zeros_like或者是np.ones_like函數直接生成一個和參考向量一樣形狀的新向量。

In [6]:
x1=np.ones((2,3))
print(x1)
print(x1.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [7]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x2=np.ones_like(x1)
print(x2)
print(x2.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(4, 3)


In [8]:
x1=np.arange(0,10,2)  #從0到10，每隔兩個取一次
print(x1)

x1=np.linspace(0,10,4)  #從0到10，總共取4個值
print(x1)


[0 2 4 6 8]
[ 0.          3.33333333  6.66666667 10.        ]


In [9]:
x1=np.eye(5)
print(x1)
print(x1.shape)

x2=np.diag((1,2,3,4,5))
print(x2)
print(x2.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
(5, 5)


In [10]:
x1=np.random.rand(10)
print(x1)

x1=np.random.normal(1,0.5,(5,2))#生成平均值為1，標準差為0.5，形狀為(5,2)的向量
print(x1)

x1=np.random.standard_normal((5,2))
print(x1)

[0.32563774 0.87055788 0.28239168 0.1251864  0.74551139 0.37528236
 0.27485355 0.67672614 0.85903842 0.69149711]
[[0.87859468 0.8028786 ]
 [1.19622475 0.19065433]
 [0.64993724 0.8132327 ]
 [1.71507432 1.41319119]
 [1.21985422 0.7198243 ]]
[[-2.03932638  0.22340357]
 [-1.87368732 -0.76005183]
 [ 1.4150207   1.78167425]
 [ 0.94791303  0.02916472]
 [-0.54746292  0.75407934]]


## ndarray索引的概念

In [11]:
x1=np.arange(0,10,2)
print(x1)

x2=x1[0] #取第0個
print(x2)

x3=x1[3]#取索引值為3，實際上為第4個
print(x3)

x4=x1[-1]#取倒數第1個
print(x4)

x5=x1[-3]#取倒數第3個
print(x5)

[0 2 4 6 8]
0
6
8
4


In [12]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x1.shape)
print(x1)

x2=x1[1] #取得第0個維度索引值為1的內容(由於第1個維度沒指定等於全取
print(x2)


x3=x1[1][2] #取得第0個維度索引值為1第1個維度索引值為2的內容
print(x3)


x4=x1[1,2] #取得第0個維度索引值為1第1個維度索引值為2的內容(與上方同等概念)
print(x4)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[4 5 6]
6
6


In [13]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x1)

x2=x1[0]
print(x2)

x3=x1[0,-1]
print(x3)

x4=x1[0,:1]
print(x4)

x5=x1[0,-2:]
print(x5)

x6=x1[1:3,:]
print(x6)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]
3
[1]
[2 3]
[[4 5 6]
 [7 8 9]]
